-- Migration 008: Remove Dead Tables (Gap #3 Solution)
-- ======================================================
--
-- RATIONALE:
-- Schema audit on 2026-02-07 identified 3 unused tables that have
-- zero code references. These tables increase database bloat, slow
-- migrations, and waste resources on unused RLS policies/indexes.
--
-- UNUSED TABLES IDENTIFIED:
-- 1. erp_variance_records  - No references found
-- 2. merkle_proofs         - No references found
-- 3. source_registry       - No references found
--
-- SAFETY:
-- - All 3 tables have zero INSERT/SELECT/UPDATE/DELETE operations
-- - No foreign key constraints reference these tables
-- - RLS policies and indexes will be dropped automatically
-- - Backup the database before running if you want to preserve data
--
-- AUDIT TRAIL:
-- This migration was generated by scripts/schema-audit.py
-- Full audit report: schema-audit-report.json
--
-- ======================================================

-- Drop unused tables (no code references)
-- ========================================

-- 1. ERP Variance Records
-- No code references - intended for future ERP posting variance tracking
-- but never implemented. If needed in future, recreate from git history.
DROP TABLE IF EXISTS erp_variance_records CASCADE;

-- 2. Merkle Proofs
-- No code references - blockchain proof feature uses 'anchors' table instead.
-- This table was likely from an earlier design iteration.
DROP TABLE IF EXISTS merkle_proofs CASCADE;

-- 3. Source Registry
-- No code references - source tracking is handled by ingestion_log table.
-- This appears to be duplicate/deprecated functionality.
DROP TABLE IF EXISTS source_registry CASCADE;

-- Verification Query
-- ===================
-- After migration, verify tables are gone:
--
-- SELECT table_name
-- FROM information_schema.tables
-- WHERE table_schema = 'public'
-- AND table_name IN ('erp_variance_records', 'merkle_proofs', 'source_registry');
--
-- Expected result: 0 rows (all tables removed)

-- Performance Impact
-- ===================
-- BEFORE: 73 tables, 3 unused (4.1% waste)
-- AFTER:  70 tables, 0 unused (0% waste)
--
-- Benefits:
-- - Faster migrations (3 fewer tables to process)
-- - Reduced RLS policy overhead
-- - Clearer schema (no dead code confusion)
-- - Smaller database backup files
