/*
 * Migration 013: Evidence Packages
 *
 * Stores evidence-driven compliance assessment packages generated by
 * the evidence-collector module. Each package contains real operational
 * data evidence for ICFR controls, PCAOB assertions, and governance frameworks.
 */

BEGIN;

CREATE TABLE IF NOT EXISTS evidence_packages (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL,
  period TEXT NOT NULL,
  package_hash TEXT NOT NULL,

  control_evidence JSONB NOT NULL DEFAULT '{}',
  pcaob_evidence JSONB NOT NULL DEFAULT '{}',
  governance_evidence JSONB NOT NULL DEFAULT '{}',
  transaction_sampling JSONB NOT NULL DEFAULT '{}',
  overall_assessment JSONB NOT NULL DEFAULT '{}',

  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  generated_by TEXT DEFAULT 'evidence-collector/1.0.0',
  audit_ready BOOLEAN DEFAULT false,

  CONSTRAINT unique_org_period_evidence UNIQUE (organization_id, period)
);

CREATE INDEX IF NOT EXISTS idx_evidence_packages_org ON evidence_packages(organization_id);
CREATE INDEX IF NOT EXISTS idx_evidence_packages_period ON evidence_packages(organization_id, period);
CREATE INDEX IF NOT EXISTS idx_evidence_packages_generated ON evidence_packages(generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_evidence_packages_audit_ready ON evidence_packages(audit_ready) WHERE audit_ready = true;

COMMENT ON TABLE evidence_packages IS 'Evidence-driven compliance assessment packages with real operational data (Solution 12)';
COMMENT ON COLUMN evidence_packages.package_hash IS 'SHA-256 hash of entire evidence package for tamper detection';
COMMENT ON COLUMN evidence_packages.audit_ready IS 'Whether this package meets audit readiness criteria';

-- Prevent UPDATE on evidence_packages (immutable once generated)
CREATE OR REPLACE FUNCTION prevent_evidence_package_update()
RETURNS TRIGGER AS $$
BEGIN
  -- Allow updating audit_ready flag only
  IF OLD.package_hash = NEW.package_hash AND
     OLD.control_evidence = NEW.control_evidence AND
     OLD.pcaob_evidence = NEW.pcaob_evidence THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION 'evidence_packages are immutable: content modification not permitted';
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS immutable_evidence_packages ON evidence_packages;
CREATE TRIGGER immutable_evidence_packages
  BEFORE UPDATE ON evidence_packages
  FOR EACH ROW EXECUTE FUNCTION prevent_evidence_package_update();

-- Track migration
INSERT INTO schema_migrations (version, description)
VALUES (13, 'Evidence Packages - Evidence-driven compliance assessment storage')
ON CONFLICT (version) DO UPDATE SET installed_on = NOW();

COMMIT;
